name = advanced_discovery_maps
title = Advanced Discovery Maps
description = An optimized fullscreen mapping GUI system featuring topographic shading, cave maps, telemetry, and waypoint sharing.
supported_games = *, minetest_game, nodecore, mineclonia, mineclone2, voxelibre
author = Koatl
