mod_name = paintings_gallery
title = Paintings Gallery
description = A bunch of carefully curated AI generated art in many styles for many build types. Now Survival friendly.
depends = default, paintings_lib, dye, wool
optional_depends = dye, wool
min_minetest_version = 5.3
