name = stelluasuna
title = StelluAsuna
author = KroXserver
description = A fusion of Asuna and Stellua with additional mods — space travel, magic, creatures, villages, and more.
disallowed_mapgens = v6
