name = shields_mtg
title = Shields
description = Adds 3D interactive shields with blocking mechanics, custom animations, and inventory support for Minetest Game / Luanti.
license = MIT (code), CC-BY-SA-3.0 (media)
depends = default
optional_depends = sfinv
author = Drix03
