name = chemistry
description = Adds liquids, gases, solids, and more things in this mod!
depends = default, tnt, bucket, basic_materials, fire, plastic_bucket
optional_depends = dynamic_liquid, doc, technic, mesecons, 3d_armor, uraniumstuff, bonemeal, climate_api, ethereal
title = Chemistry 
author = Emiliano
