name = stl_asuna_bridge
title = Stellua-Asuna Hybrid Bridge
description = Keeps Asuna as homeworld and isolates Stellua skies and physics to space
depends = stl_core, stl_vehicles
optional_depends = other_worlds

