name = simple_fishing_default
title = Simple Fishing Default
description = Default pack for Simple Fishing
depends = default, farming, simple_fishing
optional_depends = moreores, simple_materials_magic, simple_materials_technic, 3d_armor, moretrees
author = fruitsnack
